### ISSUE TITLE
part 'app_router.gr.dart'; does not exist

### ISSUE THREAD

**Issue by ghost** [codenameakshay/kai-qoohoo#3]
Hi there, I'm trying to run your project using latest flutter 3.3.10 and with vscode.

I think the pubspec is the same as you wrote it, though, so it shouldn't matter what version/s I'm using correct?

I'm getting several errors such as "The argument type 'AppRouter' can't be assigned to the parameter type 'StackRouter'." in mainldart, but I think this error (in title) seems to be at the root of it all.

I'm assuming it has to do with a missing dependency somewhere.

I would really like to get this running, thank you!

**Comment by codenameakshay** [comment]
Have you generated code? After `flutter pub get`, please run `flutter pub run build_runner build --delete-conflicting-outputs` to generate the `.gr.dart` files.

**Comment by ghost** [comment]
I don't know what that question means.  I tried that command and it finished successfuly but with some warnings about "anazlyzer versioon doen't match SDK".  The project still did not build and run after that... with more navigator/nagivation related syntax error messages in  the debug console.  I then ran "flutter packages upgrade" in order to upgrade the analyzer.   Then on the next build attempt it gave a multidex (android) 64k limit error so I changed the minSDKVerion in the app/build.gradle to 21.  Then It appears to build successfully for Android.  If it is at all possible, I am sure other beginner devs wanting to run this project would appreciate if the repo could be updated/fixed so that it would not immediately load with errors and build on the first attempt without these obstacles.

**Comment by codenameakshay** [comment]
Cool, I will update the repo to work on latest Flutter.
